version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    ports:
    - 27017:27017
    command: --smallfiles

  app:
    image: laster/todo-app
    ports:
      - 8080:8080
    links:
      - mongodb
    volumes:
      - ./logs/todo-app_logs/:/todo-app/logs/todo-app_logs/ # the path inside the container must be an absolute path