# https://medium.com/@volmar.oliveira.jr/a-restapi-using-spring-boot-mongodb-running-on-docker-containers-5e530b48f45e

version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    ports:
    - 27017:27017
    command: --smallfiles
  app:
    image: laster/todo-app
    ports:
      - 8080:8080
    links:
      - mongodb